(() => {
'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const ui={score:$('score'),coins:$('coins'),best:$('best'),hud:$('hud'),menu:$('menu'),gameOver:$('gameOver'),shop:$('shop'),missions:$('missions'),toast:$('toast'),finalScore:$('finalScore'),finalCoins:$('finalCoins'),finalBest:$('finalBest'),bankCoins:$('bankCoins'),skins:$('skins'),missionsList:$('missionsList')};
const SAVE='dogSurfSave_v2',LANES=[-280,0,280],skins=[{id:'classic',name:'Sunny Pup',emoji:'🐶',price:0},{id:'captain',name:'Captain Pup',emoji:'🧢',price:320},{id:'royal',name:'Royal Pup',emoji:'👑',price:700}];
let ysdk=null,last=0,state='menu',muted=false,adRuns=0;
const save=load(); let game=newGame();
function newGame(){return{t:0,speed:700,lane:1,x:0,targetX:0,y:0,vy:0,jumping:false,sliding:false,slide:0,invuln:0,score:0,runCoins:0,revived:false,doubleUsed:false,obstacles:[],bones:[],particles:[],spawnT:0,boneT:0};}
function load(){try{return Object.assign({best:0,coins:0,owned:['classic'],skin:'classic',missions:{collect:0,dodge:0}},JSON.parse(localStorage.getItem(SAVE)||'{}'));}catch{return{best:0,coins:0,owned:['classic'],skin:'classic',missions:{collect:0,dodge:0}};}}
function persist(){localStorage.setItem(SAVE,JSON.stringify(save));}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2); canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);} resize(); addEventListener('resize',resize);
function show(name){['menu','gameOver','shop','missions'].forEach(k=>ui[k].classList.toggle('hidden',k!==name));}
function toast(t){ui.toast.textContent=t;ui.toast.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.add('hidden'),1700);}
function start(){game=newGame();state='play';ui.hud.classList.remove('hidden');show('none');updateHud();}
function over(){state='over';save.coins+=game.runCoins;save.best=Math.max(save.best,Math.floor(game.score));persist();ui.finalScore.textContent=Math.floor(game.score);ui.finalCoins.textContent=game.runCoins;ui.finalBest.textContent=save.best;show('gameOver');adRuns++;if(adRuns%3===0)showInterstitial();}
function updateHud(){ui.score.textContent=Math.floor(game.score);ui.coins.textContent=save.coins+game.runCoins;ui.best.textContent=save.best;}
function input(act){if(state!=='play')return; if(act==='L')game.lane=Math.max(0,game.lane-1); if(act==='R')game.lane=Math.min(2,game.lane+1); if(act==='J'&&!game.jumping){game.jumping=true;game.vy=-1050;} if(act==='S'&&!game.jumping){game.sliding=true;game.slide=.55;}}
function spawnObstacle(){const lane=Math.floor(Math.random()*3),r=Math.random(),type=r<.24?'jumpRock':r<.48?'slideGate':r<.72?'laneCrab':r<.9?'movingBuoy':'combo';game.obstacles.push({lane,z:-240,type,dx:Math.random()>.5?1:-1});}
function spawnBones(){const lane=Math.floor(Math.random()*3),pat=Math.floor(Math.random()*3);for(let i=0;i<7;i++){const ln=pat===0?lane:pat===1?(i%3):((lane+i)%3);game.bones.push({lane:ln,z:-200-i*95,rare:i===3&&Math.random()<.4,taken:false});}}
function pz(z){const p=Math.max(.15,Math.min(1.6,(z+900)/1600));return{p,y:innerHeight*.25+p*innerHeight*.72};}
function update(dt){if(state!=='play')return; game.t+=dt; game.speed=Math.min(1450,game.speed+dt*20); game.score+=dt*game.speed*.05; game.targetX=LANES[game.lane]; game.x+=(game.targetX-game.x)*Math.min(1,dt*11); if(game.jumping){game.y+=game.vy*dt;game.vy+=2200*dt;if(game.y>=0){game.y=0;game.jumping=false;}} if(game.sliding){game.slide-=dt;if(game.slide<=0)game.sliding=false;} if(game.invuln>0)game.invuln-=dt;
 game.spawnT-=dt;if(game.spawnT<=0){spawnObstacle();game.spawnT=Math.max(.45,1.15-game.t*.004)+Math.random()*.2;} game.boneT-=dt;if(game.boneT<=0){spawnBones();game.boneT=.95+Math.random()*.9;}
 const dz=game.speed*dt; game.obstacles.forEach(o=>{o.z+=dz;if(o.type==='movingBuoy')o.lane=Math.max(0,Math.min(2,o.lane+(Math.random()<.04?o.dx:0)));}); game.bones.forEach(b=>b.z+=dz);
 game.obstacles=game.obstacles.filter(o=>o.z<1200); game.bones=game.bones.filter(b=>b.z<1200&&!b.taken); check(); updateHud();}
function check(){const px=game.x; for(const b of game.bones){const s=pz(b.z),x=LANES[b.lane]*s.p;if(Math.abs(x-px)<90&&Math.abs(s.y-(innerHeight*.74+game.y))<105){b.taken=true;game.runCoins+=b.rare?5:1;save.missions.collect++;}}
 if(game.invuln>0)return; for(const o of game.obstacles){const s=pz(o.z),x=LANES[o.lane]*s.p,y=Math.abs(s.y-(innerHeight*.74+game.y)); if(Math.abs(x-px)<95&&y<100){const ok=(o.type==='jumpRock'&&game.jumping)||(o.type==='slideGate'&&game.sliding); if(!ok){over();return;} save.missions.dodge++;}}}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight); drawBg(); drawLanes(); drawEntities(); drawPlayer();}
function drawBg(){const g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,'#5d78df');g.addColorStop(.3,'#ff8a64');g.addColorStop(.53,'#ffd97e');g.addColorStop(.54,'#1994d5');g.addColorStop(1,'#0a3a62');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight); ctx.fillStyle='rgba(255,233,154,.85)';ctx.beginPath();ctx.arc(innerWidth*.77,innerHeight*.18,Math.min(100,innerWidth*.08),0,7);ctx.fill();}
function drawLanes(){for(let i=0;i<3;i++){ctx.strokeStyle='rgba(255,255,255,.27)';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(innerWidth/2+LANES[i]*.2,innerHeight*.34);ctx.bezierCurveTo(innerWidth/2+LANES[i]*.6,innerHeight*.62,innerWidth/2+LANES[i],innerHeight*.95,innerWidth/2+LANES[i],innerHeight*1.1);ctx.stroke();}}
function drawEntities(){const arr=[...game.bones.map(v=>({...v,k:'b'})),...game.obstacles.map(v=>({...v,k:'o'}))].sort((a,b)=>a.z-b.z); for(const e of arr){const s=pz(e.z),x=innerWidth/2+LANES[e.lane]*s.p,y=s.y;ctx.save();ctx.translate(x,y);ctx.scale(s.p,s.p); if(e.k==='b'){ctx.fillStyle=e.rare?'#95fbff':'#ffd34d';ctx.beginPath();ctx.roundRect(-25,-16,50,32,12);ctx.fill();ctx.fillStyle='#fff';ctx.fillText('🦴',0,6);} else {ctx.font='54px serif';ctx.textAlign='center';ctx.fillText(e.type==='jumpRock'?'🪨':e.type==='slideGate'?'🌊':e.type==='laneCrab'?'🦀':'🛟',0,0);}ctx.restore();}}
function drawPlayer(){const x=innerWidth/2+game.x,y=innerHeight*.74+game.y;ctx.save();ctx.translate(x,y);const bob=Math.sin(game.t*16)*3;ctx.translate(0,bob);ctx.fillStyle='rgba(0,0,0,.2)';ctx.beginPath();ctx.ellipse(0,120,170,34,0,0,7);ctx.fill(); const surf=ctx.createLinearGradient(-140,70,140,140);surf.addColorStop(0,'#51e6df');surf.addColorStop(.5,'#ffbf42');surf.addColorStop(1,'#ff5f8c');ctx.fillStyle=surf;ctx.beginPath();ctx.ellipse(0,100,160,34,0,0,7);ctx.fill(); ctx.fillStyle='#fff5e5';ctx.beginPath();ctx.ellipse(0,20,75,88,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(-44,-35,30,50,-.3,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(44,-35,30,50,.3,0,7);ctx.fill();ctx.fillStyle='#161920';ctx.beginPath();ctx.arc(-28,-2,12,0,7);ctx.arc(28,-2,12,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-24,-6,4,0,7);ctx.arc(32,-6,4,0,7);ctx.fill();ctx.fillStyle='#202025';ctx.beginPath();ctx.ellipse(0,18,15,10,0,0,7);ctx.fill();ctx.strokeStyle='#3b2a2f';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,27,24,.15,2.95);ctx.stroke(); const sk=skins.find(s=>s.id===save.skin);if(sk?.id!=='classic'){ctx.font='34px serif';ctx.fillText(sk.emoji,0,-72);}ctx.restore();}
function loop(ts){const dt=Math.min(.033,(ts-last)/1000||0);last=ts;update(dt);draw();requestAnimationFrame(loop);} requestAnimationFrame(loop);
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','a'].includes(k))input('L');if(['arrowright','d'].includes(k))input('R');if(['arrowup','w',' '].includes(k))input('J');if(['arrowdown','s'].includes(k))input('S');});
let sx=0,sy=0;canvas.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;});canvas.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<22)return input('J');if(Math.abs(dx)>Math.abs(dy))input(dx<0?'L':'R');else input(dy<0?'J':'S');});
$('playBtn').onclick=start;$('restartBtn').onclick=start;$('homeBtn').onclick=()=>{state='menu';ui.hud.classList.add('hidden');show('menu');};$('shopBtn').onclick=()=>{renderShop();show('shop');};$('missionsBtn').onclick=()=>{renderMissions();show('missions');};$('backFromShop').onclick=() => show('menu');$('backFromMissions').onclick=()=>show('menu');$('fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
$('pauseBtn').onclick=()=>{if(state==='play'){state='pause';toast('Пауза');}else if(state==='pause'){state='play';}};$('muteBtn').onclick=()=>{muted=!muted;$('muteBtn').textContent=muted?'🔈':'🔊';};$('leaderBtn').onclick=()=>toast('Leaderboard: surfDogRushScore');
$('reviveBtn').onclick=()=>{if(game.revived)return toast('Revive уже использован');showRewarded(()=>{game.revived=true;game.invuln=3;game.obstacles=[];state='play';show('none');});};$('doubleBtn').onclick=()=>{if(game.doubleUsed)return toast('x2 уже использован');showRewarded(()=>{game.doubleUsed=true;save.coins+=game.runCoins;persist();toast('Награда удвоена');});};
function renderShop(){ui.bankCoins.textContent=save.coins;ui.skins.innerHTML='';skins.forEach(s=>{const own=save.owned.includes(s.id),d=document.createElement('div');d.className='shopItem';d.innerHTML=`<span>${s.emoji} ${s.name}<br><small>${own?'Куплено':s.price+' косточек'}</small></span>`;const b=document.createElement('button');b.textContent=save.skin===s.id?'Выбран':own?'Выбрать':'Купить';b.onclick=()=>{if(!own){if(save.coins<s.price)return toast('Не хватает косточек');save.coins-=s.price;save.owned.push(s.id);}save.skin=s.id;persist();renderShop();updateHud();};d.appendChild(b);ui.skins.appendChild(d);});}
function renderMissions(){const data=[`Собери 200 косточек: ${save.missions.collect}/200`,`Уклонись от 100 преград: ${save.missions.dodge}/100`,`Поставь рекорд 5000+: ${save.best}/5000`];ui.missionsList.innerHTML=data.map(v=>`<li>${v}</li>`).join('');}
async function initY(){if(!window.YaGames)return; try{ysdk=await YaGames.init();ysdk.features.LoadingAPI?.ready();}catch{}}
function showInterstitial(){ysdk?.adv?.showFullscreenAdv({callbacks:{}});} function showRewarded(ok){if(!ysdk?.adv){ok();return;}ysdk.adv.showRewardedVideo({callbacks:{onRewarded:ok,onError:()=>toast('Реклама недоступна')}});} 
initY();show('menu');updateHud();
})();
